#!/bin/bash

SIP_FILE=$(realpath "$1");
SIP_ADDRESS="$2";

CMD="docker run --mount type=bind,source=$SIP_FILE,target=/SIPconfig.xml  koha-sip2-cli-docker test_sip.pl /SIPconfig.xml $SIP_ADDRESS"
#echo $CMD;
${CMD};

